// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class filezz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(filezz));
        
        string IMigrationMetadata.Id
        {
            get { return "201501222321552_filezz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
